notifications:
  email: false

language: ruby
cache: bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

before_install:
  - test -d config/environments || mkdir -p config/environments
  - cp config/environments/example.rb config/environments/development.rb
